version: "3"

services:
  server:
    build:
      context: ./..
      dockerfile: ./.devcontainer/server/Dockerfile
    volumes:
      - ./../:/app
      - node_modules:/app/node_modules
    restart: always
    tty: true

volumes:
  node_modules:
